version: '3'
services:
  namenode:
    build: .
    ports:
      - "50070:50070"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=test
  datanode:
    build: .
    ports:
      - "50075:50075"
    environment:
      - CLUSTER_NAME=test
