version: '3'
services:
  spark:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark:7077
  worker:
    build: .
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
